version: '3'

services:
  backend:
    image: 2023bcd0015/2023bcd15_backend
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    image: 2023bcd0015/2023bcd15_frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend