FROM jenkins:lts

USER root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    git \
    jq \
    bc \
    docker.io \
 && rm -rf /var/lib/apt/lists/*

USER jenkins